import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://sewago-final.vercel.app';
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/services',
          '/about',
          '/contact',
          '/faqs',
          '/pricing',
          '/performance',
          '/service-bundles',
          '/search',
          '/careers',
          '/press',
          '/support',
          '/how-it-works',
          '/terms',
          '/privacy',
          '/sitemap.xml',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/account/',
          '/provider/',
          '/bookings/',
          '/chat/',
          '/notifications/',
          '/settings/',
          '/wallet/',
          '/verification/',
          '/auth/',
          '/_next/',
          '/demo/',
          '/*.json',
          '/*.xml',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/account/',
          '/provider/',
          '/bookings/',
          '/chat/',
          '/notifications/',
          '/settings/',
          '/wallet/',
          '/verification/',
          '/auth/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/account/',
          '/provider/',
          '/bookings/',
          '/chat/',
          '/notifications/',
          '/settings/',
          '/wallet/',
          '/verification/',
          '/auth/',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
