[build]
builder = "nixpacks"
root = "backend"

[deploy]
start_command = "npm start"
health_check_path = "/api/health"
health_check_timeout = 300
restart_policy_type = "on_failure"
restart_policy_max_retries = 3

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"

# Railway will automatically set PORT - don't override it

