[build]
builder = "nixpacks"
root = "backend"

[deploy]
start_command = "npm start"
health_check_path = "/api/health"
health_check_timeout = 30
restart_policy_type = "on_failure"
restart_policy_max_retries = 3

[env]
NODE_ENV = "production"
PORT = "8080"
NIXPACKS_NODE_VERSION = "20"

# Performance optimizations
[env.NODE_OPTIONS]
value = "--max-old-space-size=1024 --optimize-for-size"

[env.UV_THREADPOOL_SIZE]
value = "128"
