[build]
builder = "nixpacks"
root = "backend"

[deploy]
start_command = "npm start"
health_check_path = "/api/health"
health_check_timeout = 300

[env]
NODE_ENV = "production"
PORT = "8080"
NIXPACKS_NODE_VERSION = "20"

