services:
  - type: web
    name: sewago-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: https://sewago-final.vercel.app
      - key: MONGODB_URI
        fromSecret: MONGODB_URI